// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:c75c67cc-19ae-4478-a9d5-8ff8b87c87c8",
    "aws_cognito_region": "eu-west-1",
    "aws_mobile_analytics_app_id": "75045c404180410fa527f0e0fa3099ce",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_content_delivery_bucket": "teachat-20181130121615--hostingbucket",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://teachat-20181130121615--hostingbucket.s3-website-eu-west-1.amazonaws.com"
};


export default awsmobile;
